services:
  sampleissuer:
    image: 442426876549.dkr.ecr.eu-west-1.amazonaws.com/etuitus/mdl-issuer:0.2.7-DEMO-IPZS
    container_name: sampleissuer
    environment:
      CBOR_SERVICE_URL: "http://cborservice:8080/v1/signed-mdoc-credentials/mdl"
      SERVICE_URL: "SPECIFY_YOUR_SERVICE_URL_HERE"
    networks:
      - backend
    depends_on:
      - cborservice

  cborservice:
    image: 442426876549.dkr.ecr.eu-west-1.amazonaws.com/etuitus/cbor-service:2025.07.29
    container_name: cborservice
    environment:
      LOG_LEVEL: "DEBUG"
      SIGN_API_URL: "https://iot-mtls.infocert.digital"
      SIGN_MTLS_CERTIFICATE: "/etc/certs/pki/cbor_service.crt"
      SIGN_MTLS_KEY: "/etc/certs/pki/cbor_service.key"
      SIGN_API_PATH: "/iot/rest/v1/cipher/InfoCert/IPZS/sign"
      COSE_ALGORITHM: ES256
    volumes:
      - ./certs/pki:/etc/certs/pki:ro
    networks:
      - backend