version: "3.8"

services:
  infocert-ewc-srv:
    platform: linux/amd64
    image: public.ecr.aws/dizme.io/eulsp/infocert-srv-web-issuing-eudiw-py:0.1.0-DEMO-ITB
    container_name: infocert-ewc-srv
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app"
      FLASK_RUN_PORT: "5000"
      FLASK_RUN_HOST: "0.0.0.0"
      SERVICE_URL: "SERVICE_URL (PUT / AT THE END)"
      FLASK_SECRET_KEY: "Rfyp=BxBeq"
      REVOCATION_API_KEY: ""
      TOP_AUTH_CLIENT_ID: "TOP_AUTH_CLIENT_ID"
      TOP_AUTH_CLIENT_SECRET: "TOP_AUTH_CLIENT_SECRET"
      HMAC_SECRET: ""
    command: >
      sh -c "/root/eudi-srv-web-issuing-eudiw-py/venv/bin/flask run"
